README.md, charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/application-env.yaml, charts/dso-env/values.yaml
=> feat: :sparkles: use dso-ns chart version in dso-env chart

charts/dso-console/.helmignore, charts/dso-console/Chart.lock, charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/_helpers.tpl, charts/dso-console/templates/client/configmap.yaml, charts/dso-console/templates/client/deployment.yaml, charts/dso-console/templates/client/hpa.yaml, charts/dso-console/templates/client/secret.yaml, charts/dso-console/templates/client/service.yaml, charts/dso-console/templates/config.yaml, charts/dso-console/templates/ingress.yaml, charts/dso-console/templates/pullsecret.yml, charts/dso-console/templates/server/clusterrole.yaml, charts/dso-console/templates/server/clusterrolebinding.yaml, charts/dso-console/templates/server/configmap.yaml, charts/dso-console/templates/server/deployment.yaml, charts/dso-console/templates/server/hpa.yaml, charts/dso-console/templates/server/scripts.yaml, charts/dso-console/templates/server/secret.yaml, charts/dso-console/templates/server/service.yaml, charts/dso-console/templates/server/serviceaccount.yaml, charts/dso-console/values.yaml
---------
Ajout du nouveau chart de la console.
Non.
=> feat: :sparkles: add cloud-pi-native console helm chart

.github/workflows/ci.yaml, .github/workflows/release.yaml
---------
Ajoute le dépôt Helm Bitnami pour pouvoir publier le nouveau chart de la Console.
Non.
=> ci: :construction_worker: add bitnami helm repo chart in ci

.github/workflows/ci.yaml, charts/dso-console/templates/server/scripts.yaml
=> fix: :bug: override plugins if exists in console chart

charts/dso-console/Chart.yaml, charts/dso-console/README.md
---------
Passe les images de la console en `v8.2.0`.
Non.
=> chore: :arrow_up: upgrade console chart with v8.2.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md
---------
Passe les images de la console en `v8.2.1`.
Non.
=> chore: :arrow_up: upgrade console chart with app v8.2.1

charts/dso-console/Chart.yaml, charts/dso-console/README.md
---------
Nouvelle version du chart avec la version `v8.2.2` de la console.
Non.
=> chore: :arrow_up: upgrade console chart with app v8.2.2

charts/dso-console/Chart.yaml, charts/dso-console/README.md
---------
Nouvelle version du chart avec la version `v8.3.0` de la console.
Non.
=> chore: :arrow_up: upgrade console chart with app v8.3.0

charts/dso-env/templates/project-env.yaml
=> fix: :bug: allow helm-charts as source repo

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/client/deployment.yaml, charts/dso-console/templates/cnpg/scheduled-backup.yaml, charts/dso-console/templates/server/deployment.yaml
=> fix: :bug: console chart templates

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/client/deployment.yaml, charts/dso-console/templates/server/deployment.yaml, charts/dso-console/values.yaml
=> feat: :sparkles: add envfrom values in console chart

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: new console release

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/cnpg/pg-cluster.yaml, charts/dso-console/values.yaml
=> feat: :sparkles: add nameoverride for console chart cnpg cluster

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/server/deployment.yaml
=> fix: :bug: missing global vconf on init fetch

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console chart with app v8.4.1

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: console v8.5.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console version to v8.6.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console version

charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/application-app.yaml, charts/dso-env/values.yaml
---------
Besoin d'un attribut name pour chaque repo
Le nom est calculé à partir de l'url du repo
=> feat: :sparkles: calculate app name from repo url

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: bump dso-console version to 8.8.2

charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/pg-cluster.yaml, charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/cnpg/pg-cluster.yaml
=> fix: :bug: add missing database and owner keys in restore mode

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: bump dso-console version to 8.9.0

charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/application-app.yaml, charts/dso-env/values.yaml
=> feat: :sparkles: use value files for Helm detected repository

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console to v8.9.2

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/keycloak/configmap.yaml, charts/dso-console/values.yaml
=> chore: :wrench: add optional dev realm configmap deployment

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/keycloak/configmap.yaml
=> fix: :bug: keycloak dev realm configmap

charts/dso-backup-utils/Chart.yaml, charts/dso-backup-utils/README.md, charts/dso-backup-utils/templates/_helpers.tpl, charts/dso-backup-utils/templates/postgresql/configmap.yaml, charts/dso-backup-utils/templates/postgresql/cronjob.yaml, charts/dso-backup-utils/templates/postgresql/secret.yaml, charts/dso-backup-utils/templates/pullsecret.yml, charts/dso-backup-utils/templates/vault/configmap.yaml, charts/dso-backup-utils/templates/vault/cronjob.yaml, charts/dso-backup-utils/templates/vault/secret.yaml, charts/dso-backup-utils/values.yaml
=> feat: :sparkles: add backup-utils chart

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/keycloak/configmap.yaml
=> chore: :arrow_up: upgrade console to v8.9.3

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade console to v8.9.4

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: ⬆️ upgrade console to v8.10.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: ⬆️ upgrade console to v8.10.1

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: ⬆️ upgrade console to v8.11.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: ⬆️ upgrade console to v8.11.1

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/server/configmap.yaml, charts/dso-console/templates/server/deployment.yaml
=> fix: :bug: force use generated secret if cnpg enabled

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/server/deployment.yaml
=> fix: :bug: oups bad container

charts/dso-console/Chart.yaml, charts/dso-console/README.md
Nouvelle version du chart lié à la nouvelle version `8.12.0` de la console.
=> chore: :arrow_up: upgrade console to v8.12.0

.github/workflows/update-chart.yaml
=> build: 👷 add worflow to update chart

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/cnpg/pg-cluster.yaml, charts/dso-console/values.yaml
Il n'est pas possible de gérer la compression des backups CNPG dans le chart de la Console.
Une `values` permet désormais de gérer la compression des backups CNPG.
Non.
=> feat: :sparkles: handle cnpg backup compression in console chart

charts/dso-infra-argocd/Chart.lock, charts/dso-infra-argocd/Chart.yaml, charts/dso-infra-argocd/README.md, charts/dso-infra-argocd/values.yaml
---------
Pas de SSO
SSO fonctionnel avec le clientID créé automatiquement par la console à la déclaration / mise à jour de la zone
=> feat: Adding mandatory values to configure Keycloak OIDC

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/server/deployment.yaml, charts/dso-console/values.yaml
=> feat: enable fetch plugins container image customization

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/server/deployment.yaml, charts/dso-console/values.yaml
=> fix: :bug: enable fetch plugins container pull policy customization

charts/dso-console/README.md, charts/dso-console/templates/server/clusterrole.yaml, charts/dso-console/templates/server/configmap.yaml, charts/dso-console/values.yaml
=> refactor: :recycle: support for disabling vault-secrets

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/ingress.yaml
=> feat: :sparkles: add swagger-ui ingress config

charts/dso-console/Chart.yaml, charts/dso-console/README.md
=> chore: :arrow_up: upgrade dso-console to 9.0.0

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/cnpg/pg-cluster.yaml, charts/dso-console/values.yaml
Il est possible de configurer pour le cluster CNPG du chart de la Console :
- `recoveryTarget`
- `maxParallelWal`
Non.
=> feat: :sparkles: add cnpg values in dso-console chart

charts/dso-cnpg/Chart.lock, charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/backup-secret-ca.yaml, charts/dso-cnpg/templates/backup-secret-creds.yaml, charts/dso-cnpg/templates/pg-cluster.yaml, charts/dso-cnpg/values.yaml
Amélioration de la configuration du chart `dso-cnpg` (pas utilisé de notre côté pour l'instant mais surement une bonne idée d'aller vers ça avec le Gitops pour centraliser la maintenance).
Oui, quelques clés sont renommées.
=> refactor: :recycle: improve dso-cnpg chart config

charts/observatorium/Chart.yaml, charts/observatorium/README.md
=> chore: add maintainer on observatorium chart

charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/backup-secret-ca.yaml, charts/dso-cnpg/templates/backup-secret-creds.yaml, charts/dso-cnpg/templates/pg-cluster.yaml, charts/dso-cnpg/templates/scheduled-backup.yaml, charts/dso-cnpg/values.yaml
Issues numéro:  https://github.com/cloud-pi-native/socle/issues/490
---------
- `apiVersion` typo.
- Missing `imagePullSecrets`.
- Missing `{{- if eq .Values.mode "primary" }}` for `pg_hba`.
- Missing enabling of PodMonitor.
- Indentation error.
- `template.*` instead of `cpnCnpg.*`
Fix of all the above.
No.
Related PR : https://github.com/cloud-pi-native/socle/pull/492
=> fix: :bug: cpn-cnpg charts

charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/pooler.yaml, charts/dso-cnpg/values.yaml
---------
Possibilité de déployer un kind cnpg Pooler
=> feat: :sparkles: add pooler option to deploy pgbouncer

charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/podmonitor.yaml, charts/dso-cnpg/values.yaml
https://github.com/cloud-pi-native/socle/issues/487
https://github.com/cloud-pi-native/socle/issues/490
---------
Not possible to use podmonitor labels values.
Enable the use of podmonitor labels values.
No.
Related to https://github.com/cloud-pi-native/socle/pull/522
=> feat: :sparkles: add podmonitor template

charts/dso-grafana/Chart.yaml, charts/dso-grafana/README.md
=> feat: Add grafana-operator dependency

charts/dso-grafana/Chart.yaml, charts/dso-grafana/README.md, charts/dso-grafana/templates/default_dashboards.yaml
=> fix dashboard syntax

charts/dso-cnpg/Chart.yaml, charts/dso-cnpg/README.md, charts/dso-cnpg/templates/pg-cluster.yaml
---------
`Failed sync attempt to a1fbe18f9744ffff28f3e37461e27924d47ed435: one or more objects failed to apply, reason: Cluster.postgresql.cnpg.io "pg-cluster-harbor" is invalid: [spec.backup.barmanObjectStore.endpointCA.key: Invalid value: "null": spec.backup.barmanObjectStore.endpointCA.key in body must be of type string: "null", spec.backup.barmanObjectStore.endpointCA.name: Invalid value: "null": spec.backup.barmanObjectStore.endpointCA.name in body must be of type string: "null", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation] (retried 5 times).`
Fix the above.
No.
No.
=> fix: :bug: missing condition for endpointCA

charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/project-app.yaml, charts/dso-env/templates/project-env.yaml, charts/dso-env/values.yaml
---------
Un seul source repo peut être configuré sur le AppProject
Possibilité de passer une liste de source repositories
=> feat: use a source repositories list

charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/project-app.yaml, charts/dso-env/templates/project-env.yaml, charts/dso-env/values.yaml
=> feat: fix and rename source repositories list

charts/dso-env/Chart.yaml, charts/dso-env/README.md, charts/dso-env/templates/project-app.yaml, charts/dso-env/templates/project-env.yaml
=> fix: source repos attribute name

charts/dso-grafana/Chart.yaml, charts/dso-grafana/README.md, charts/dso-grafana/templates/custom_dashboards.yaml, charts/dso-grafana/values.yaml
=> feat: Add an argocd Application to deploy custom dashboards

charts/dso-ansible-job/Chart.yaml, charts/dso-ansible-job/README.md, charts/dso-ansible-job/templates/_helpers.tpl, charts/dso-ansible-job/templates/job.yaml
Issues numéro: https://github.com/cloud-pi-native/console/issues/1633, https://github.com/cloud-pi-native/socle/issues/646
---------
```
failed to create typed patch object (dso-gitlab/sdid-hp-dso-gitlaboperator-cpn-ansible-job; batch/v1, Kind=CronJob): .spec.jobTemplate.spec.template.spec.labels: field not declared in schema
```
Fix the above.
No.
No.
=> fix: :bug: labels field

charts/dso-ns/Chart.yaml, charts/dso-ns/README.md, charts/dso-ns/templates/vso-auth.yaml
=> feat: :wrench: ignore VaultConnection when Vault url is empty

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/_helpers.tpl, charts/dso-console/templates/server/deployment.yaml, charts/dso-console/templates/server/secret.yaml, charts/dso-console/values.yaml
---------
L'utilisation du secret cnpg est conditionné au déploiement du sous-chart CNPG
Utilisation d'un nouvel attribut pour utiliser (ou non) le secret CNPG
=> feat: :art: use cnpg secret name optional attribute

charts/dso-ansible-job/Chart.yaml, charts/dso-ansible-job/README.md, charts/dso-ansible-job/templates/_helpers.tpl
=> fix: :zap: moving imagepullpolicy to always

charts/dso-ansible-job/Chart.yaml, charts/dso-ansible-job/README.md, charts/dso-ansible-job/templates/_helpers.tpl, charts/dso-ansible-job/values.yaml
=> fix: :bug: add missing parameter to choose the right DSC

charts/dso-ansible-job/Chart.yaml, charts/dso-ansible-job/README.md, charts/dso-ansible-job/templates/_helpers.tpl, charts/dso-ansible-job/values.yaml
Issues numéro: https://github.com/cloud-pi-native/socle/issues/465
---------
Chart does not support extra Volumes nor the override of image pull policy.
Implement the above.
No.
No.
=> feat: :sparkles: add extraVolumes, extraVolumeMounts and image.pullPolicy

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/templates/client/configmap.yaml, charts/dso-console/templates/server/configmap.yaml, charts/dso-console/values.yaml
Issues numéro: https://github.com/cloud-pi-native/socle/issues/465
---------
`KEYCLOAK_DOMAIN` is the same for backend and frontend.
Make the possibility for `KEYCLOAK_DOMAIN` to be different for backend and frontend.
No.
No.
=> fix: :wrench: dissociate back and front domain

charts/dso-grafana/Chart.yaml, charts/dso-grafana/README.md, charts/dso-grafana/templates/custom_resources.yaml
=> fix: disable appproject when no envs is configured in the project

charts/dso-grafana/Chart.yaml, charts/dso-grafana/README.md, charts/dso-grafana/templates/custom_resources.yaml
=> fix: invalid syntax on multiple projects

charts/dso-observability/Chart.yaml, charts/dso-observability/README.md, charts/dso-observability/templates/_rules.yaml
=> fix: missing subdirectory in glob pattern

charts/dso-console/Chart.yaml, charts/dso-console/README.md, charts/dso-console/values.yaml
=> fix: :ambulance: move to bitnami legacy images
